# Experimental results for adaptive air caution

In [1]:
#import libraries
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from os import path, listdir
from IPython.display import Video

In [2]:
# set file path
data_dir = path.join('data','scaledCushion_1-2', '31-05-2022')
data_dir_list = listdir(data_dir)
print('Data directory: {}'.format(data_dir))
print('Files in data data directory: {}\n'.format(data_dir_list))

crio_data_dir = path.join(data_dir, 'data_crio')
shimmer_data_dir = path.join(data_dir, 'data_shimmer')
movies_data_dir = path.join(data_dir, 'movies')

# get list of files
crio_dir_list = listdir(crio_data_dir)
shimmer_dir_list = listdir(shimmer_data_dir)
movies_dir_list = listdir(movies_data_dir)
file_names = pd.DataFrame()
file_names['data_crio'] = crio_dir_list
file_names['data_shimmer'] = shimmer_dir_list
file_names['data_movies'] = movies_dir_list
print('List of files:')
file_names

Data directory: data/scaledCushion_1-2/31-05-2022
Files in data data directory: ['data_crio', 'movies', 'data_shimmer']

List of files:

             data_crio        data_shimmer         data_movies
0   h3500_m10_vo_2.lvm  h1500_m10_vo_2.txt   h2500_m5_vc_2.mp4
1    h1500_m5_vc_1.lvm  h1500_m10_vo_1.txt   h2500_m5_vc_1.mp4
2   h3500_m10_vo_1.lvm   h1500_m5_vo_2.txt   h3500_m5_vc_1.mp4
3    h1500_m5_vc_2.lvm  h3500_m10_vc_1.txt  h2500_m10_vo_1.mp4
4   h1500_m10_vc_1.lvm   h1500_m5_vo_1.txt   h3500_m5_vc_2.mp4
5   h1500_m10_vc_2.lvm  h3500_m10_vc_2.txt  h2500_m10_vo_2.mp4
6    h2500_m5_vc_1.lvm   h3500_m5_vo_1.txt   h1500_m5_vc_2.mp4
7    h2500_m5_vc_2.lvm  h2500_m10_vc_1.txt  h3500_m10_vo_1.mp4
8   h2500_m10_vo_2.lvm   h3500_m5_vo_2.txt   h1500_m5_vc_1.mp4
9    h3500_m5_vc_2.lvm  h2500_m10_vc_2.txt  h3500_m10_vo_2.mp4
10  h2500_m10_vo_1.lvm   h2500_m5_vo_2.txt  h1500_m10_vc_2.mp4
11   h3500_m5_vc_1.lvm   h2500_m5_vo_1.txt  h1500_m10_vc_1.mp4
12   h3500_m5_vo_1.lvm   h2500_m5_vc_1.txt  h1500_m10_vo_1.mp4
13  h2500_m10_vc_1.lvm   h2500_m5_vc_2.txt  h1500_m10_vo_2.mp4
14   h3500_m5_vo_2.lvm  h2500_m10_vo_2.txt  h3500_m10_vc_2.mp4
15  h2500_m10_vc_2.lvm   h3500_m5_vc_2.txt   h1500_m5_vo_1.mp4
16   h2500_m5_vo_2.lvm  h2500_m10_vo_1.txt  h3500_m10_vc_1.mp4
17   h2500_m5_vo_1.lvm   h3500_m5_vc_1.txt   h1500_m5_vo_2.mp4
18  h1500_m10_vo_2.lvm  h3500_m10_vo_2.txt  h2500_m10_vc_2.mp4
19  h1500_m10_vo_1.lvm   h1500_m5_vc_1.txt   h3500_m5_vo_2.mp4
20   h1500_m5_vo_2.lvm  h3500_m10_vo_1.txt  h2500_m10_vc_1.mp4
21  h3500_m10_vc_1.lvm   h1500_m5_vc_2.txt   h3500_m5_vo_1.mp4
22   h1500_m5_vo_1.lvm  h1500_m10_vc_1.txt   h2500_m5_vo_1.mp4
23  h3500_m10_vc_2.lvm  h1500_m10_vc_2.txt   h2500_m5_vo_2.mp4

In [6]:
# load data from c-rio
crio_file_name = file_names['data_crio'][0]
crio_data = pd.read_csv(path.join(crio_data_dir, crio_file_name), sep='\t', header = None)
print(np.shape(crio_data))
crio_data.drop([0, 9], axis = 1, inplace=True)
crio_data.columns = ['Top chamber pressure', 'Bottom chamber pressure','Air frame pressure',\
                     'Absolute pressure', 'Force 1', 'Force 2',\
                     'Force 3', 'Force 4']
crio_data.head()

#file_name = 'zrzut_m10kg_h3500_v1-4_1.txt'

(5000, 10)

,Top chamber pressure,Bottom chamber pressure,Air frame pressure,Absolute pressure,Force 1,Force 2,Force 3,Force 4
0,-0.546092,-0.402428,164.154059,1006.806768,324.928192,54.439610,101.661236,239.049634
1,0.237903,-0.209508,162.676610,1007.627730,321.423889,54.597614,98.793161,252.186972
2,-0.033006,0.024460,163.004932,1008.161355,321.583175,53.491589,101.183223,252.186972
3,-0.209508,0.299474,163.087013,1008.120307,321.423889,52.701572,99.430511,278.461649
4,-0.295706,0.521127,164.236140,1006.149999,321.742462,52.069558,98.952499,317.873663

In [8]:
# load data from shimmer
shimmer_file_name = file_names['data_shimmer'][0]
shimmer_data = pd.read_csv(path.join(shimmer_data_dir, shimmer_file_name), sep='\t')
shimmer_data.head()

,Timestamp,PC Timestamp,Low Noise Accelerometer X,Low Noise Accelerometer Y,Low Noise Accelerometer Z,Int A12,Int A13,Int A14,Gyroscope X,Gyroscope Y,Gyroscope Z,Wide Range Accelerometer X,Wide Range Accelerometer Y,Wide Range Accelerometer Z
0,101815.338,NaN,0.109,5.707,-5.707,1509.158,1500.366,1498.901,-1.038,0.061,-1.038,-2.297,4.211,-8.268
1,101816.315,NaN,0.120,5.696,-5.707,1510.623,1500.366,1497.436,-1.069,0.183,-0.992,-2.373,4.211,-8.268
2,101817.291,NaN,0.130,5.685,-5.717,1509.158,1501.099,1497.436,-1.115,0.260,-1.130,-2.297,4.134,-8.268
3,101818.268,NaN,0.130,5.696,-5.707,1510.623,1502.564,1498.901,-1.145,0.198,-1.267,-2.144,4.211,-8.191
4,101819.244,NaN,0.120,5.685,-5.728,1510.623,1501.832,1498.901,-1.344,0.229,-1.359,-2.220,4.364,-8.191